import { Theme, ThemeId } from './types';

export const THEMES: Record<ThemeId, Theme> = {
  neon_shadow: {
    id: 'neon_shadow',
    name: 'Neon Shadow',
    cost: 0,
    primary: '#00ffcc',
    secondary: '#ffaa00',
    bg: '#000000',
    lockColor: '#00ffcc',
    scanlineOpacity: 0.08,
    glitchColor: '#ff00ff',
    description: 'Default. Amber terminals, cyan locks. Classic heist noir.',
  },
  retro_terminal: {
    id: 'retro_terminal',
    name: 'Retro Terminal',
    cost: 150,
    primary: '#39ff14',
    secondary: '#00ff00',
    bg: '#0a0a00',
    lockColor: '#39ff14',
    scanlineOpacity: 0.15,
    glitchColor: '#ffff00',
    description: 'Old phosphor green. Heavy scanlines. Pure vintage hacker.',
  },
  ghost_protocol: {
    id: 'ghost_protocol',
    name: 'Ghost Protocol',
    cost: 250,
    primary: '#a0e8ff',
    secondary: '#ffffff',
    bg: '#020510',
    lockColor: '#a0e8ff',
    scanlineOpacity: 0.05,
    glitchColor: '#4488ff',
    description: 'Ice blue, near-invisible. You were never here.',
  },
  blood_vault: {
    id: 'blood_vault',
    name: 'Blood Vault',
    cost: 300,
    primary: '#ff2244',
    secondary: '#ff6600',
    bg: '#0d0000',
    lockColor: '#ff2244',
    scanlineOpacity: 0.12,
    glitchColor: '#ff0000',
    description: 'Crimson and fire. High stakes, maximum danger.',
  },
  void_runner: {
    id: 'void_runner',
    name: 'Void Runner',
    cost: 400,
    primary: '#cc44ff',
    secondary: '#8800ff',
    bg: '#050008',
    lockColor: '#cc44ff',
    scanlineOpacity: 0.1,
    glitchColor: '#ff00cc',
    description: 'Deep purple void. The abyss stares back.',
  },
  quantum_breach: {
    id: 'quantum_breach',
    name: 'Quantum Breach',
    cost: 500,
    primary: '#00ffff',
    secondary: '#ff00ff',
    bg: '#000810',
    lockColor: '#00ffff',
    scanlineOpacity: 0.07,
    glitchColor: '#ffffff',
    description: 'Dual-spectrum quantum encryption. Reality is optional.',
  },
};

export const THEME_LIST: Theme[] = Object.values(THEMES);
